# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loss_analysis.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1115, 793)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.tableView = QtWidgets.QTableView(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableView.sizePolicy().hasHeightForWidth())
        self.tableView.setSizePolicy(sizePolicy)
        self.tableView.setMinimumSize(QtCore.QSize(600, 600))
        self.tableView.setObjectName("tableView")
        self.gridLayout.addWidget(self.tableView, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.odds = QtWidgets.QLabel(Form)
        self.odds.setObjectName("odds")
        self.horizontalLayout.addWidget(self.odds)
        self.spinBox = QtWidgets.QSpinBox(Form)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout.addWidget(self.spinBox)
        self.maximum_loss = QtWidgets.QLabel(Form)
        self.maximum_loss.setObjectName("maximum_loss")
        self.horizontalLayout.addWidget(self.maximum_loss)
        self.lineEdit = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.label = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.data_del = QtWidgets.QPushButton(Form)
        self.data_del.setObjectName("data_del")
        self.horizontalLayout.addWidget(self.data_del)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.total_throw_label = QtWidgets.QLabel(Form)
        self.total_throw_label.setObjectName("total_throw_label")
        self.gridLayout.addWidget(self.total_throw_label, 3, 0, 1, 1)
        self.total_catch_label = QtWidgets.QLabel(Form)
        self.total_catch_label.setObjectName("total_catch_label")
        self.gridLayout.addWidget(self.total_catch_label, 4, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 5, 0, 1, 1)
        self.total_money = QtWidgets.QLabel(Form)
        self.total_money.setObjectName("total_money")
        self.gridLayout.addWidget(self.total_money, 2, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.odds.setText(_translate("Form", "赔率"))
        self.maximum_loss.setText(_translate("Form", "最大预亏损"))
        self.pushButton.setText(_translate("Form", "分析"))
        self.label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600;\">投注总金额为：</span></p></body></html>"))
        self.data_del.setText(_translate("Form", "清除数据"))
        self.total_throw_label.setText(_translate("Form", "总抛出金额为："))
        self.total_catch_label.setText(_translate("Form", "总吃进金额为："))
        self.total_money.setText(_translate("Form", "投注总金额为："))
